//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.19 at 06:58:12 PM IST 
//


package org.example.brokers;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageFlow_TYP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageFlow_TYP">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.example.org/Brokers}MessageFlowName"/>
 *         &lt;element ref="{http://www.example.org/Brokers}MessageFlowVersion"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageFlow_TYP", propOrder = {
    "messageFlowName",
    "messageFlowVersion"
})
public class MessageFlowTYP {

    @XmlElement(name = "MessageFlowName", required = true)
    protected String messageFlowName;
    @XmlElement(name = "MessageFlowVersion", required = true)
    protected String messageFlowVersion;

    /**
     * Gets the value of the messageFlowName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageFlowName() {
        return messageFlowName;
    }

    /**
     * Sets the value of the messageFlowName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageFlowName(String value) {
        this.messageFlowName = value;
    }

    /**
     * Gets the value of the messageFlowVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageFlowVersion() {
        return messageFlowVersion;
    }

    /**
     * Sets the value of the messageFlowVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageFlowVersion(String value) {
        this.messageFlowVersion = value;
    }

}
