//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.19 at 06:58:12 PM IST 
//


package org.example.brokers;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.example.brokers package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MessageFlows_QNAME = new QName("http://www.example.org/Brokers", "MessageFlows");
    private final static QName _Broker_QNAME = new QName("http://www.example.org/Brokers", "Broker");
    private final static QName _ExecutionGroups_QNAME = new QName("http://www.example.org/Brokers", "ExecutionGroups");
    private final static QName _ApplicationName_QNAME = new QName("http://www.example.org/Brokers", "ApplicationName");
    private final static QName _Applications_QNAME = new QName("http://www.example.org/Brokers", "Applications");
    private final static QName _ExecutionGroupName_QNAME = new QName("http://www.example.org/Brokers", "ExecutionGroupName");
    private final static QName _Brokers_QNAME = new QName("http://www.example.org/Brokers", "Brokers");
    private final static QName _ExecutionGroup_QNAME = new QName("http://www.example.org/Brokers", "ExecutionGroup");
    private final static QName _IsApplicationRunning_QNAME = new QName("http://www.example.org/Brokers", "isApplicationRunning");
    private final static QName _MessageFlowName_QNAME = new QName("http://www.example.org/Brokers", "MessageFlowName");
    private final static QName _MessageFlow_QNAME = new QName("http://www.example.org/Brokers", "MessageFlow");
    private final static QName _BrokerName_QNAME = new QName("http://www.example.org/Brokers", "BrokerName");
    private final static QName _IsBrokerRunning_QNAME = new QName("http://www.example.org/Brokers", "isBrokerRunning");
    private final static QName _IsExecutionGroupRunning_QNAME = new QName("http://www.example.org/Brokers", "isExecutionGroupRunning");
    private final static QName _ApplicationDeployedOn_QNAME = new QName("http://www.example.org/Brokers", "ApplicationDeployedOn");
    private final static QName _EnvironmentAlias_QNAME = new QName("http://www.example.org/Brokers", "EnvironmentAlias");
    private final static QName _Application_QNAME = new QName("http://www.example.org/Brokers", "Application");
    private final static QName _MessageFlowVersion_QNAME = new QName("http://www.example.org/Brokers", "MessageFlowVersion");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.example.brokers
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ApplicationTYP }
     * 
     */
    public ApplicationTYP createApplicationTYP() {
        return new ApplicationTYP();
    }

    /**
     * Create an instance of {@link MessageFlowTYP }
     * 
     */
    public MessageFlowTYP createMessageFlowTYP() {
        return new MessageFlowTYP();
    }

    /**
     * Create an instance of {@link BrokerTYP }
     * 
     */
    public BrokerTYP createBrokerTYP() {
        return new BrokerTYP();
    }

    /**
     * Create an instance of {@link ExecutionGroupsTYP }
     * 
     */
    public ExecutionGroupsTYP createExecutionGroupsTYP() {
        return new ExecutionGroupsTYP();
    }

    /**
     * Create an instance of {@link ApplicationsTYP }
     * 
     */
    public ApplicationsTYP createApplicationsTYP() {
        return new ApplicationsTYP();
    }

    /**
     * Create an instance of {@link BrokersTYP }
     * 
     */
    public BrokersTYP createBrokersTYP() {
        return new BrokersTYP();
    }

    /**
     * Create an instance of {@link MessageFlowsTYP }
     * 
     */
    public MessageFlowsTYP createMessageFlowsTYP() {
        return new MessageFlowsTYP();
    }

    /**
     * Create an instance of {@link ExecutionGroupTYP }
     * 
     */
    public ExecutionGroupTYP createExecutionGroupTYP() {
        return new ExecutionGroupTYP();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageFlowsTYP }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Brokers", name = "MessageFlows")
    public JAXBElement<MessageFlowsTYP> createMessageFlows(MessageFlowsTYP value) {
        return new JAXBElement<MessageFlowsTYP>(_MessageFlows_QNAME, MessageFlowsTYP.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BrokerTYP }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Brokers", name = "Broker")
    public JAXBElement<BrokerTYP> createBroker(BrokerTYP value) {
        return new JAXBElement<BrokerTYP>(_Broker_QNAME, BrokerTYP.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExecutionGroupsTYP }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Brokers", name = "ExecutionGroups")
    public JAXBElement<ExecutionGroupsTYP> createExecutionGroups(ExecutionGroupsTYP value) {
        return new JAXBElement<ExecutionGroupsTYP>(_ExecutionGroups_QNAME, ExecutionGroupsTYP.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Brokers", name = "ApplicationName")
    public JAXBElement<String> createApplicationName(String value) {
        return new JAXBElement<String>(_ApplicationName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicationsTYP }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Brokers", name = "Applications")
    public JAXBElement<ApplicationsTYP> createApplications(ApplicationsTYP value) {
        return new JAXBElement<ApplicationsTYP>(_Applications_QNAME, ApplicationsTYP.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Brokers", name = "ExecutionGroupName")
    public JAXBElement<String> createExecutionGroupName(String value) {
        return new JAXBElement<String>(_ExecutionGroupName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BrokersTYP }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Brokers", name = "Brokers")
    public JAXBElement<BrokersTYP> createBrokers(BrokersTYP value) {
        return new JAXBElement<BrokersTYP>(_Brokers_QNAME, BrokersTYP.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExecutionGroupTYP }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Brokers", name = "ExecutionGroup")
    public JAXBElement<ExecutionGroupTYP> createExecutionGroup(ExecutionGroupTYP value) {
        return new JAXBElement<ExecutionGroupTYP>(_ExecutionGroup_QNAME, ExecutionGroupTYP.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Brokers", name = "isApplicationRunning")
    public JAXBElement<Boolean> createIsApplicationRunning(Boolean value) {
        return new JAXBElement<Boolean>(_IsApplicationRunning_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Brokers", name = "MessageFlowName")
    public JAXBElement<String> createMessageFlowName(String value) {
        return new JAXBElement<String>(_MessageFlowName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MessageFlowTYP }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Brokers", name = "MessageFlow")
    public JAXBElement<MessageFlowTYP> createMessageFlow(MessageFlowTYP value) {
        return new JAXBElement<MessageFlowTYP>(_MessageFlow_QNAME, MessageFlowTYP.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Brokers", name = "BrokerName")
    public JAXBElement<String> createBrokerName(String value) {
        return new JAXBElement<String>(_BrokerName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Brokers", name = "isBrokerRunning")
    public JAXBElement<Boolean> createIsBrokerRunning(Boolean value) {
        return new JAXBElement<Boolean>(_IsBrokerRunning_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Brokers", name = "isExecutionGroupRunning")
    public JAXBElement<Boolean> createIsExecutionGroupRunning(Boolean value) {
        return new JAXBElement<Boolean>(_IsExecutionGroupRunning_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Brokers", name = "ApplicationDeployedOn")
    public JAXBElement<String> createApplicationDeployedOn(String value) {
        return new JAXBElement<String>(_ApplicationDeployedOn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Brokers", name = "EnvironmentAlias")
    public JAXBElement<String> createEnvironmentAlias(String value) {
        return new JAXBElement<String>(_EnvironmentAlias_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplicationTYP }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Brokers", name = "Application")
    public JAXBElement<ApplicationTYP> createApplication(ApplicationTYP value) {
        return new JAXBElement<ApplicationTYP>(_Application_QNAME, ApplicationTYP.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Brokers", name = "MessageFlowVersion")
    public JAXBElement<String> createMessageFlowVersion(String value) {
        return new JAXBElement<String>(_MessageFlowVersion_QNAME, String.class, null, value);
    }

}
