//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.07 at 07:47:52 PM IST 
//


package com.cts.dnb.model5;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cts.dnb.model5 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RequestType_QNAME = new QName("http://www.example.org/Requests", "RequestType");
    private final static QName _Request_QNAME = new QName("http://www.example.org/Requests", "Request");
    private final static QName _RequestID_QNAME = new QName("http://www.example.org/Requests", "RequestID");
    private final static QName _RequestStatus_QNAME = new QName("http://www.example.org/Requests", "RequestStatus");
    private final static QName _Requests_QNAME = new QName("http://www.example.org/Requests", "Requests");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cts.dnb.model5
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestsTYP }
     * 
     */
    public RequestsTYP createRequestsTYP() {
        return new RequestsTYP();
    }

    /**
     * Create an instance of {@link RequestTYP }
     * 
     */
    public RequestTYP createRequestTYP() {
        return new RequestTYP();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Requests", name = "RequestType")
    public JAXBElement<String> createRequestType(String value) {
        return new JAXBElement<String>(_RequestType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestTYP }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Requests", name = "Request")
    public JAXBElement<RequestTYP> createRequest(RequestTYP value) {
        return new JAXBElement<RequestTYP>(_Request_QNAME, RequestTYP.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Requests", name = "RequestID")
    public JAXBElement<String> createRequestID(String value) {
        return new JAXBElement<String>(_RequestID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Requests", name = "RequestStatus")
    public JAXBElement<String> createRequestStatus(String value) {
        return new JAXBElement<String>(_RequestStatus_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestsTYP }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/Requests", name = "Requests")
    public JAXBElement<RequestsTYP> createRequests(RequestsTYP value) {
        return new JAXBElement<RequestsTYP>(_Requests_QNAME, RequestsTYP.class, null, value);
    }

}
