//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.24 at 01:59:36 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/Users", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cts.dnb.model4;
