//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.23 at 06:24:32 PM IST 
//


package com.cts.dnb.model3;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.cts.dnb.model3 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _QMpassword_QNAME = new QName("http://www.example.org/QMs", "QMpassword");
    private final static QName _QMchannel_QNAME = new QName("http://www.example.org/QMs", "QMchannel");
    private final static QName _Queue_QNAME = new QName("http://www.example.org/QMs", "queue");
    private final static QName _Topic_QNAME = new QName("http://www.example.org/QMs", "topic");
    private final static QName _Channel_QNAME = new QName("http://www.example.org/QMs", "Channel");
    private final static QName _ConnectConfig_QNAME = new QName("http://www.example.org/QMs", "ConnectConfig");
    private final static QName _QMusername_QNAME = new QName("http://www.example.org/QMs", "QMusername");
    private final static QName _QMname_QNAME = new QName("http://www.example.org/QMs", "QMname");
    private final static QName _QueueManager_QNAME = new QName("http://www.example.org/QMs", "QueueManager");
    private final static QName _Queues_QNAME = new QName("http://www.example.org/QMs", "queues");
    private final static QName _QMhost_QNAME = new QName("http://www.example.org/QMs", "QMhost");
    private final static QName _QMport_QNAME = new QName("http://www.example.org/QMs", "QMport");
    private final static QName _Channels_QNAME = new QName("http://www.example.org/QMs", "Channels");
    private final static QName _Environment_QNAME = new QName("http://www.example.org/QMs", "environment");
    private final static QName _Topics_QNAME = new QName("http://www.example.org/QMs", "topics");
    private final static QName _QueueManagers_QNAME = new QName("http://www.example.org/QMs", "QueueManagers");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.cts.dnb.model3
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QueueManagers }
     * 
     */
    public QueueManagers createQueueManagers() {
        return new QueueManagers();
    }

    /**
     * Create an instance of {@link ConnectConfig }
     * 
     */
    public ConnectConfig createConnectConfig() {
        return new ConnectConfig();
    }

    /**
     * Create an instance of {@link Channels }
     * 
     */
    public Channels createChannels() {
        return new Channels();
    }

    /**
     * Create an instance of {@link QueueManager }
     * 
     */
    public QueueManager createQueueManager() {
        return new QueueManager();
    }

    /**
     * Create an instance of {@link Queues }
     * 
     */
    public Queues createQueues() {
        return new Queues();
    }

    /**
     * Create an instance of {@link Topics }
     * 
     */
    public Topics createTopics() {
        return new Topics();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/QMs", name = "QMpassword")
    public JAXBElement<String> createQMpassword(String value) {
        return new JAXBElement<String>(_QMpassword_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/QMs", name = "QMchannel")
    public JAXBElement<String> createQMchannel(String value) {
        return new JAXBElement<String>(_QMchannel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/QMs", name = "queue")
    public JAXBElement<String> createQueue(String value) {
        return new JAXBElement<String>(_Queue_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/QMs", name = "topic")
    public JAXBElement<String> createTopic(String value) {
        return new JAXBElement<String>(_Topic_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/QMs", name = "Channel")
    public JAXBElement<String> createChannel(String value) {
        return new JAXBElement<String>(_Channel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConnectConfig }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/QMs", name = "ConnectConfig")
    public JAXBElement<ConnectConfig> createConnectConfig(ConnectConfig value) {
        return new JAXBElement<ConnectConfig>(_ConnectConfig_QNAME, ConnectConfig.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/QMs", name = "QMusername")
    public JAXBElement<String> createQMusername(String value) {
        return new JAXBElement<String>(_QMusername_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/QMs", name = "QMname")
    public JAXBElement<String> createQMname(String value) {
        return new JAXBElement<String>(_QMname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueueManager }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/QMs", name = "QueueManager")
    public JAXBElement<QueueManager> createQueueManager(QueueManager value) {
        return new JAXBElement<QueueManager>(_QueueManager_QNAME, QueueManager.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Queues }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/QMs", name = "queues")
    public JAXBElement<Queues> createQueues(Queues value) {
        return new JAXBElement<Queues>(_Queues_QNAME, Queues.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/QMs", name = "QMhost")
    public JAXBElement<String> createQMhost(String value) {
        return new JAXBElement<String>(_QMhost_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/QMs", name = "QMport")
    public JAXBElement<String> createQMport(String value) {
        return new JAXBElement<String>(_QMport_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Channels }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/QMs", name = "Channels")
    public JAXBElement<Channels> createChannels(Channels value) {
        return new JAXBElement<Channels>(_Channels_QNAME, Channels.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/QMs", name = "environment")
    public JAXBElement<String> createEnvironment(String value) {
        return new JAXBElement<String>(_Environment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Topics }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/QMs", name = "topics")
    public JAXBElement<Topics> createTopics(Topics value) {
        return new JAXBElement<Topics>(_Topics_QNAME, Topics.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueueManagers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/QMs", name = "QueueManagers")
    public JAXBElement<QueueManagers> createQueueManagers(QueueManagers value) {
        return new JAXBElement<QueueManagers>(_QueueManagers_QNAME, QueueManagers.class, null, value);
    }

}
