//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.23 at 06:24:32 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/QMs", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.cts.dnb.model3;
