//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.23 at 06:24:32 PM IST 
//


package com.cts.dnb.model3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QueueManager complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QueueManager">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.example.org/QMs}environment"/>
 *         &lt;element ref="{http://www.example.org/QMs}ConnectConfig"/>
 *         &lt;element ref="{http://www.example.org/QMs}queues"/>
 *         &lt;element ref="{http://www.example.org/QMs}Channels"/>
 *         &lt;element ref="{http://www.example.org/QMs}topics"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QueueManager", propOrder = {
    "environment",
    "connectConfig",
    "queues",
    "channels",
    "topics"
})
public class QueueManager {

    @XmlElement(required = true)
    protected String environment;
    @XmlElement(name = "ConnectConfig", required = true)
    protected ConnectConfig connectConfig;
    @XmlElement(required = true)
    protected Queues queues;
    @XmlElement(name = "Channels", required = true)
    protected Channels channels;
    @XmlElement(required = true)
    protected Topics topics;

    /**
     * Gets the value of the environment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnvironment() {
        return environment;
    }

    /**
     * Sets the value of the environment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnvironment(String value) {
        this.environment = value;
    }

    /**
     * Gets the value of the connectConfig property.
     * 
     * @return
     *     possible object is
     *     {@link ConnectConfig }
     *     
     */
    public ConnectConfig getConnectConfig() {
        return connectConfig;
    }

    /**
     * Sets the value of the connectConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConnectConfig }
     *     
     */
    public void setConnectConfig(ConnectConfig value) {
        this.connectConfig = value;
    }

    /**
     * Gets the value of the queues property.
     * 
     * @return
     *     possible object is
     *     {@link Queues }
     *     
     */
    public Queues getQueues() {
        return queues;
    }

    /**
     * Sets the value of the queues property.
     * 
     * @param value
     *     allowed object is
     *     {@link Queues }
     *     
     */
    public void setQueues(Queues value) {
        this.queues = value;
    }

    /**
     * Gets the value of the channels property.
     * 
     * @return
     *     possible object is
     *     {@link Channels }
     *     
     */
    public Channels getChannels() {
        return channels;
    }

    /**
     * Sets the value of the channels property.
     * 
     * @param value
     *     allowed object is
     *     {@link Channels }
     *     
     */
    public void setChannels(Channels value) {
        this.channels = value;
    }

    /**
     * Gets the value of the topics property.
     * 
     * @return
     *     possible object is
     *     {@link Topics }
     *     
     */
    public Topics getTopics() {
        return topics;
    }

    /**
     * Sets the value of the topics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Topics }
     *     
     */
    public void setTopics(Topics value) {
        this.topics = value;
    }

}
