//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.23 at 06:24:32 PM IST 
//


package com.cts.dnb.model3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ConnectConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ConnectConfig">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.example.org/QMs}QMname"/>
 *         &lt;element ref="{http://www.example.org/QMs}QMhost"/>
 *         &lt;element ref="{http://www.example.org/QMs}QMport"/>
 *         &lt;element ref="{http://www.example.org/QMs}QMchannel"/>
 *         &lt;element ref="{http://www.example.org/QMs}QMusername"/>
 *         &lt;element ref="{http://www.example.org/QMs}QMpassword"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ConnectConfig", propOrder = {
    "qMname",
    "qMhost",
    "qMport",
    "qMchannel",
    "qMusername",
    "qMpassword"
})
public class ConnectConfig {

    @XmlElement(name = "QMname", required = true)
    protected String qMname;
    @XmlElement(name = "QMhost", required = true)
    protected String qMhost;
    @XmlElement(name = "QMport", required = true)
    protected String qMport;
    @XmlElement(name = "QMchannel", required = true)
    protected String qMchannel;
    @XmlElement(name = "QMusername", required = true)
    protected String qMusername;
    @XmlElement(name = "QMpassword", required = true)
    protected String qMpassword;

    /**
     * Gets the value of the qMname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQMname() {
        return qMname;
    }

    /**
     * Sets the value of the qMname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQMname(String value) {
        this.qMname = value;
    }

    /**
     * Gets the value of the qMhost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQMhost() {
        return qMhost;
    }

    /**
     * Sets the value of the qMhost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQMhost(String value) {
        this.qMhost = value;
    }

    /**
     * Gets the value of the qMport property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQMport() {
        return qMport;
    }

    /**
     * Sets the value of the qMport property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQMport(String value) {
        this.qMport = value;
    }

    /**
     * Gets the value of the qMchannel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQMchannel() {
        return qMchannel;
    }

    /**
     * Sets the value of the qMchannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQMchannel(String value) {
        this.qMchannel = value;
    }

    /**
     * Gets the value of the qMusername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQMusername() {
        return qMusername;
    }

    /**
     * Sets the value of the qMusername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQMusername(String value) {
        this.qMusername = value;
    }

    /**
     * Gets the value of the qMpassword property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQMpassword() {
        return qMpassword;
    }

    /**
     * Sets the value of the qMpassword property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQMpassword(String value) {
        this.qMpassword = value;
    }

}
