//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v3.0-03/04/2009 09:20 AM(valikov)-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.24 at 03:39:28 PM IST 
//


package com.cts.dnb.model1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MessageFlow_TYP complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MessageFlow_TYP">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.example.org/Brokers}MessageFlowName"/>
 *         &lt;element ref="{http://www.example.org/Brokers}MessageFlowVersion"/>
 *         &lt;element ref="{http://www.example.org/Brokers}isMessageFlowRunning"/>
 *         &lt;element ref="{http://www.example.org/Brokers}MessageFlowInstances"/>
 *         &lt;element ref="{http://www.example.org/Brokers}Queues"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MessageFlow_TYP", propOrder = {
    "messageFlowName",
    "messageFlowVersion",
    "isMessageFlowRunning",
    "messageFlowInstances",
    "queues"
})
public class MessageFlowTYP {

    @XmlElement(name = "MessageFlowName", required = true)
    protected String messageFlowName;
    @XmlElement(name = "MessageFlowVersion", required = true)
    protected String messageFlowVersion;
    protected boolean isMessageFlowRunning;
    @XmlElement(name = "MessageFlowInstances")
    protected int messageFlowInstances;
    @XmlElement(name = "Queues", required = true)
    protected QueuesTYP queues;

    /**
     * Gets the value of the messageFlowName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageFlowName() {
        return messageFlowName;
    }

    /**
     * Sets the value of the messageFlowName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageFlowName(String value) {
        this.messageFlowName = value;
    }

    /**
     * Gets the value of the messageFlowVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessageFlowVersion() {
        return messageFlowVersion;
    }

    /**
     * Sets the value of the messageFlowVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessageFlowVersion(String value) {
        this.messageFlowVersion = value;
    }

    /**
     * Gets the value of the isMessageFlowRunning property.
     * 
     */
    public boolean isIsMessageFlowRunning() {
        return isMessageFlowRunning;
    }

    /**
     * Sets the value of the isMessageFlowRunning property.
     * 
     */
    public void setIsMessageFlowRunning(boolean value) {
        this.isMessageFlowRunning = value;
    }

    /**
     * Gets the value of the messageFlowInstances property.
     * 
     */
    public int getMessageFlowInstances() {
        return messageFlowInstances;
    }

    /**
     * Sets the value of the messageFlowInstances property.
     * 
     */
    public void setMessageFlowInstances(int value) {
        this.messageFlowInstances = value;
    }

    /**
     * Gets the value of the queues property.
     * 
     * @return
     *     possible object is
     *     {@link QueuesTYP }
     *     
     */
    public QueuesTYP getQueues() {
        return queues;
    }

    /**
     * Sets the value of the queues property.
     * 
     * @param value
     *     allowed object is
     *     {@link QueuesTYP }
     *     
     */
    public void setQueues(QueuesTYP value) {
        this.queues = value;
    }

}
